# Generated by Django 4.2.5 on 2023-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('crdt_date', models.DateTimeField()),
                ('category', models.CharField(max_length=200)),
                ('is_deposit', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
                ('account_number', models.CharField(max_length=100)),
                ('target_name', models.CharField(max_length=100)),
            ],
        ),
    ]
